### ISSUE TITLE
Plan to release

### ISSUE THREAD

**Issue by gbytedev** [iksteen/LinxShare#5]
Are there any plans to release this to the android market and if not, would you be so kind and provide build instructions in the readme file?

**Comment by tuxx** [comment]
Ive just created the metadata for an fdroid app, hopefully this app will be available in the next week or so on fdroid.

https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7381

**Comment by km4joj** [comment]
I found the OpenAPSDocs had good instructions for building their app with Android-studio that was general building instructions. It actually wasnt that difficult; just install android-studio, make your signing keys, build apk.

https://pickmy.org/LinxShare.apk is where I keep my current builds. Feel free to grab it if its not on fdroid.

**Comment by iksteen** [comment]
I've set up a github actions workflow to automatically build an apk and upload it when we tag a new release.

f.e. https://github.com/iksteen/LinxShare/releases/tag/v1.0

Android might complain about not knowing the publishers key when installing it, I think that's because the apk is signed with a release key that's not known to google play.

**Comment by km4joj** [comment]
> Android might complain about not knowing the publishers key when installing it, I think that's because the apk is signed with a release key that's not known to google play

I seem to recall outside of the security prompt for external installation, I got two additional from android about not recognizing the self-signed key and one from Google Play about not recognizing the app. 

Has there been any consideration in getting this on Google Play in the future?

**Comment by iksteen** [comment]
Should be available in the play store now. https://play.google.com/store/apps/details?id=org.thegraveyard.linxshare
