### ISSUE TITLE
Failed to upload to linx-server

### ISSUE THREAD

**Issue by gbytedev** [iksteen/LinxShare#8]
Thank you for the first release!
Unfortunately I am getting the error message "Failed to upload to linx-server, check settings!" when trying to upload anything.

I am able to upload via web interface as well as via terminal with this command:
curl -H "Linx-Api-Key: xxxx" -T test.txt http://linx-domain:1234/upload/

**App settings:**
Linx URL: http://linx-domain:1234/ (representation)
API key: xxxx

**Linx server settings (docker container):**
bind = 127.0.0.1:8080
sitename = some name
siteurl = http://linx-domain:1234/
selifpath = s
maxsize = 1073741824
#maxexpiry = 86400
allowhotlink = false
remoteuploads = false
nologs = true
force-random-filename = false
cleanup-every-minutes = 720
authfile = /data/users
basicauth = true

**I tried:**
Changing Linx Url app setting to http://linx-domain:1234/upload/ - same error
Removing the need for API key on server and adjusting the app settings - same error
Setting the port on server to 80 and adjusting app settings - same error

Any pointers on what I am doing wrong?

**Comment by iksteen** [comment]
First of all, thanks for trying our app and the detailed bug report.

Any chance you can provide me with the details of your server (hostname + API key) so I can properly debug it? You can send the details out of band to iksteen@gmail.com. If this is unacceptable, which I would understand, I'll try to replicate your set-up and hopefully trigger the same issue.

**Comment by gbytedev** [comment]
Thanks a lot for your quick response! I sent you an email with the details and am looking forward to your support.

**Comment by iksteen** [comment]
The issue is that Android 9 and up don't allow non-SSL connections. #9 enables non-SSL connection from LinxShare.

**Comment by gbytedev** [comment]
@iksteen Not sure if this is related with the cause you found, but I am getting the above same error message on Android 7 and 8 while on my daily driver phone with Android 10 things work perfectly. I haven't enabled an SSL connection on the server yet though.

**Comment by djmattyg007** [comment]
I'm getting this message on Android 8, and I do have SSL fully enabled.

**Comment by djmattyg007** [comment]
It's worth noting that the photos I'm uploading are being uploaded, it's just that the app isn't recognising this for some reason.
